tensorflow-gpu 2.4.0 depends on h5py~=2.10.0 (#5301)
ERROR: Cannot install -r ./DeepFaceLab/requirements-cuda.txt (line 9) and h5py==2.9.0 because these package versions have conflicting dependencies.   

The conflict is caused by:
    The user requested h5py==2.9.0
    tensorflow-gpu 2.4.0 depends on h5py~=2.10.0